server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://database-poquiz.cla6ac8agdvp.ap-northeast-2.rds.amazonaws.com:3306/pokemon_quiz?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: rhdidtl1!

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.ssafy.pokemon.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.ssafy.pokemon : info

springdoc:
  api-docs:
    tags-group-order:
      - "User"
      - "Pokemon"
      - "RankLow"
      - "RankNormal"
      - "RankHigh"

